parameters:
- name: serviceConnectionName
  type: string
- name: environmentName
  type: string
- name: resourceGroupName
  type: string
- name: appServiceNames
  type: object
  default: []

stages:
 - stage: Deploy
   displayName: Deploy

   jobs:
   - job: Deploy
     displayName: Deploy
     variables: 
       infraTemplate: $(Pipeline.Workspace)/infrastructure/main.json
       parameterFile: '@$(Pipeline.Workspace)/infrastructure/parameters/${{ parameters.environmentName }}/parameters.json'
     steps:
     - ${{ each appServiceName in parameters.appServiceNames }}:
       - task: AzureResourceGroupDeployment@2
         displayName: Deploy ${{ appServiceName }} to ${{ parameters.environmentName }}
         inputs:
           azureSubscription: ${{ parameters.serviceConnectionName }}
           resourceGroupName: ${{ parameters.resourceGroupName }}
           csmFile: $(infraTemplate)
           csmParametersFile: $(parameterFile)
           overrideParameters: '-appServiceName ${{ appServiceName }}'