parameters:
- name: serviceConnectionName
  type: string
- name: environmentName
  type: string
- name: resourceGroupName
  type: string
- name: appServiceNames
  type: object
  default: []

stages:
 - stage: Deploy
   displayName: Deploy

   jobs:
   - job: Deploy
     displayName: Deploy
     variables: 
       infraTemplate: $(Pipeline.Workspace)/infrastructure/main.json
       parameterFile: '@$(Pipeline.Workspace)/infrastructure/parameters/${{ parameters.environmentName }}/parameters.json'
     steps:
     - download: current
       artifact: infrastructure
       displayName: Download Infrastructure
     - download: current
       artifact: functionapp
       displayName: Download Function App
     - script: |
         REGIONS=$(jq -r .parameters.regions.value $(Pipeline.Workspace)/infrastructure/parameters/${{ parameters.environmentName }}/parameters.json)
         BASE_NAME=$(jq -r .parameters.baseName.value $(Pipeline.Workspace)/infrastructure/parameters/${{ parameters.environmentName }}/parameters.json)
         APP_SERVICE_NAMES=$(jq -r --arg baseName "$BASE_NAME" '.parameters.regions.value | map($baseName + . + "fa")' $(Pipeline.Workspace)/infrastructure/parameters/${{ parameters.environmentName }}/parameters.json)
         echo $APP_SERVICE_NAMES
         echo "##vso[task.setvariable variable=appServiceNames;isoutput=true]$APP_SERVICE_NAMES"
       displayName: Set Regions
     - script: |
         echo $(appServiceNames)
       displayName: Print ASNs
     - ${{ each appServiceName in variables.appServiceNames }}:
      # Deploy function app
       - task: AzureCLI@2
         displayName: Deploy Function to ${{ appServiceName }}
         inputs:
           azureSubscription: ${{ parameters.serviceConnectionName }}
           scriptType: bash
           scriptLocation: inlineScript
           inlineScript: |
             az functionapp deployment source config-zip -g ${{ parameters.resourceGroupName }} -n ${{ appServiceName }} --src $(Pipeline.Workspace)/functionapp/functionapp.zip
