parameters:
- name: serviceConnectionName
  type: string
- name: environmentName
  type: string
- name: resourceGroupName
  type: string

stages:
 - stage: Deploy
   displayName: Deploy

   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: ${{ parameters.environmentName }}
     variables: 
       infraTemplate: $(Pipeline.Workspace)/infrastructure/main.json
       parameterFile: '@$(Pipeline.Workspace)/infrastructure/parameters/${{ parameters.environmentName }}/parameters.json'
     strategy:
       runOnce:
         deploy:
           steps:
           - download: current
             artifact: infrastructure
             displayName: 'Download Infrastructure Artifact'

           - task: AzureCLI@2
             displayName: 'Deploy Infrastructure'
             inputs:
               azureSubscription: ${{ parameters.serviceConnectionName }}
               scriptType: 'bash'
               scriptLocation: 'inlineScript'
               inlineScript: |
                 DEPLOYMENT_NAME=$(Build.BuildId)
                 az deployment group create -n $DEPLOYMENT_NAME --template-file $(infraTemplate) -g ${{ parameters.resourceGroupName }} --parameters $(parameterFile)