parameters:
- name: serviceConnectionName
  type: string
- name: environmentName
  type: string
- name: resourceGroupName
  type: string
- name: baseName
  type: string
  default: ''
- name: regions
  type: object
  default: []

stages:
 - stage: Deploy
   displayName: Deploy

   jobs:
   - job: PreDeploy
     displayName: Pre-Deploy
     variables: 
       infraTemplate: $(Pipeline.Workspace)/infrastructure/main.json
       parameterFile: '$(Pipeline.Workspace)/infrastructure/parameters/${{ parameters.environmentName }}/parameters.json'
     steps:
     - download: current
       artifact: infrastructure
       displayName: Download Infrastructure
     - download: current
       artifact: functionapp
       displayName: Download Function App
     - script: |
         echo $(infraTemplate)
         echo $(parameterFile)

     - task: AzureResourceManagerTemplateDeployment@3
       displayName: Deploy Infrastructure
       inputs:
         deploymentScope: Resource Group
         azureResourceManagerConnection: ${{ parameters.serviceConnectionName }}
         resourceGroupName: ${{ parameters.resourceGroupName }}
         location: 'West Europe'
         csmFile: $(infraTemplate)
         csmParametersFile: $(parameterFile)
         deploymentMode: Incremental
         deploymentName: ${{ parameters.baseName }}-infra
      
     - ${{ each region in parameters.regions }}:
      # Deploy function app
       - task: AzureCLI@2
         displayName: Deploy Function to ${{ region }}
         inputs:
           azureSubscription: ${{ parameters.serviceConnectionName }}
           scriptType: bash
           scriptLocation: inlineScript
           inlineScript: |
             az functionapp deployment source config-zip -g ${{ parameters.resourceGroupName }} -n ${{ parameters.baseName }}-${{ region }}-fa --src $(Pipeline.Workspace)/functionapp/functionapp.zip
